# Generated by Django 3.1.5 on 2021-04-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('files_name', models.CharField(max_length=200)),
                ('files_id', models.IntegerField(primary_key=True, serialize=False)),
                ('files_createat', models.DateTimeField()),
            ],
            options={
                'db_table': 'Files',
                'managed': False,
            },
        ),
    ]
