# Generated by Django 3.1.5 on 2021-04-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={},
        ),
    ]
