# Generated by Django 3.1.5 on 2021-04-09 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('group_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_user_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'group_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_firstname', models.CharField(max_length=200)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_lastname', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
            ],
            options={
                'db_table': 'accounts_userprofile_role',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', max_length=2000)),
                ('avatar', models.URLField(blank=True, default='')),
                ('name', models.CharField(default='', max_length=32)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='user.user')),
            ],
        ),
    ]
